"""empty message

Revision ID: 23dc3d903183
Revises: None
Create Date: 2016-05-12 10:06:22.397436

"""

# revision identifiers, used by Alembic.
revision = '23dc3d903183'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('vdc_id', sa.Integer(), nullable=False),
    sa.Column('check_in_mac_addr', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    ### end Alembic commands ###
