/*
* Generated file
*
* Generated from: yang module name: odl-sal-netconf-connector-cfg yang module local name: sal-netconf-connector
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Nov 05 12:03:41 PST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.connector.netconf;
public class YangModuleCapabilities {
    private org.opendaylight.controller.config.api.DependencyResolver dependencyResolver;

    private java.util.List<java.lang.String> capability;

    public YangModuleCapabilities () {
        super();
    }

    public void injectDependencyResolver(org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        this.dependencyResolver = dependencyResolver;
    }

    public java.util.List<java.lang.String> getCapability() {
        return capability;
    }

    public void setCapability(java.util.List<java.lang.String> capability) {
        this.capability = capability;
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(capability);

    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        final YangModuleCapabilities that = (YangModuleCapabilities) o;
        if(java.util.Objects.equals(capability, that.capability) == false) {
            return false;
        }

        return true;

    }

}
