# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkid', models.TextField()),
                ('snode', models.TextField()),
                ('dnode', models.TextField()),
                ('srcPort', models.TextField()),
                ('dstPort', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OFNodeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeid', models.TextField()),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('profile', models.TextField()),
                ('mac', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SCApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.TextField()),
                ('nodeId', models.TextField()),
                ('scInstanceId', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='NodeTable',
        ),
        migrations.DeleteModel(
            name='scBinding',
        ),
        migrations.RenameField(
            model_name='scinstance',
            old_name='Protocol',
            new_name='instid',
        ),
        migrations.RenameField(
            model_name='sctemplate',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sctemplate',
            old_name='Pipe',
            new_name='pipe',
        ),
        migrations.RemoveField(
            model_name='scinstance',
            name='ProPort',
        ),
        migrations.RemoveField(
            model_name='scinstance',
            name='scInsID',
        ),
        migrations.RemoveField(
            model_name='scinstance',
            name='tmpID',
        ),
        migrations.RemoveField(
            model_name='sctemplate',
            name='scTemID',
        ),
        migrations.AddField(
            model_name='scinstance',
            name='port',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scinstance',
            name='proto',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scinstance',
            name='tpltID',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sctemplate',
            name='tpltid',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
